export default () =>[{
  "province_name": "Margaritelli",
  "province_id": 1
}, {
  "province_name": "Sarfati",
  "province_id": 2
}, {
  "province_name": "Prestage",
  "province_id": 3
}, {
  "province_name": "Duffield",
  "province_id": 4
}, {
  "province_name": "Kreutzer",
  "province_id": 5
}, {
  "province_name": "MacLese",
  "province_id": 6
}, {
  "province_name": "Alam",
  "province_id": 7
}, {
  "province_name": "Friar",
  "province_id": 8
}, {
  "province_name": "Klimuk",
  "province_id": 9
}, {
  "province_name": "Duiged",
  "province_id": 10
}, {
  "province_name": "Jerred",
  "province_id": 11
}, {
  "province_name": "Motton",
  "province_id": 12
}, {
  "province_name": "Aymer",
  "province_id": 13
}, {
  "province_name": "Sleney",
  "province_id": 14
}, {
  "province_name": "Newbury",
  "province_id": 15
}]